#!/usr/bin/env python3
"""
Learning Curves Plotting Script for MLMORP Reinforcement Learning

This script analyzes simulation data and plots learning curves for the MLMORP
routing protocol with online reinforcement learning, including:
- Packet Delivery Ratio (PDR) over time
- Average delay over time  
- Energy efficiency over time
- Reward progression over time

The script processes the output.csv file generated by OMNeT++ simulations
and creates comprehensive visualization of the learning progress.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.ndimage import uniform_filter1d
import argparse
import os
from collections import defaultdict

class LearningCurvePlotter:
    def __init__(self, window_size=100):
        """
        Initialize the learning curve plotter
        
        Args:
            window_size: Size of moving average window for smoothing
        """
        self.window_size = window_size
        self.data = None
        
    def load_data(self, csv_file):
        """
        Load simulation data from CSV file
        
        Args:
            csv_file: Path to the output.csv file from OMNeT++ simulation
        """
        print(f"Loading data from {csv_file}...")
        
        try:
            # Try to load with headers first
            df = pd.read_csv(csv_file)
            
            # If no headers, define them
            if df.columns[0].startswith('Unnamed') or not isinstance(df.columns[0], str):
                df = pd.read_csv(csv_file, header=None)
                columns = [
                    'simTime', 'treeId', 'sourceAddress', 'destAddress',
                    'srcMacAddress', 'destMacAddress', 'nodeDegree', 'residualEnergy',
                    'dataRate', 'signalPower', 'buffPktNo'
                ]
                df.columns = columns[:len(df.columns)]
                
        except FileNotFoundError:
            print(f"Error: File {csv_file} not found!")
            return False
        except Exception as e:
            print(f"Error loading data: {e}")
            return False
        
        # Handle missing columns
        if 'signalPower' not in df.columns:
            df['signalPower'] = 1e-6
        if 'buffPktNo' not in df.columns:
            df['buffPktNo'] = 10.0
        
        # Convert simTime to numeric if it's not already
        df['simTime'] = pd.to_numeric(df['simTime'], errors='coerce')
        
        # Remove any rows with NaN simTime
        df = df.dropna(subset=['simTime'])
        
        # Sort by simulation time
        df = df.sort_values('simTime').reset_index(drop=True)
        
        self.data = df
        print(f"Loaded {len(df)} data points covering {df['simTime'].min():.2f}s to {df['simTime'].max():.2f}s")
        
        return True
    
    def calculate_pdr_over_time(self, time_window=10.0):
        """
        Calculate Packet Delivery Ratio over time
        
        Args:
            time_window: Time window for PDR calculation (seconds)
            
        Returns:
            times: Array of time points
            pdrs: Array of PDR values
        """
        if self.data is None:
            return [], []
        
        # Define destination MAC (packets that reach this are considered delivered)
        target_dest_mac = '0A-AA-00-00-00-02'
        
        # Get time range
        min_time = self.data['simTime'].min()
        max_time = self.data['simTime'].max()
        
        times = []
        pdrs = []
        
        current_time = min_time + time_window
        while current_time <= max_time:
            # Get data in current time window
            window_data = self.data[
                (self.data['simTime'] >= current_time - time_window) &
                (self.data['simTime'] < current_time)
            ]
            
            if len(window_data) > 0:
                # Count unique packets (treeIds) in this window
                unique_packets = set(window_data['treeId'])
                
                # Count delivered packets
                delivered_packets = set(
                    window_data[window_data['destMacAddress'] == target_dest_mac]['treeId']
                )
                
                # Calculate PDR
                pdr = len(delivered_packets) / len(unique_packets) if unique_packets else 0
                
                times.append(current_time)
                pdrs.append(pdr * 100)  # Convert to percentage
            
            current_time += time_window / 2  # Overlap windows for smoother curves
        
        return np.array(times), np.array(pdrs)
    
    def calculate_delay_over_time(self, time_window=10.0):
        """
        Calculate average packet delay over time
        
        Args:
            time_window: Time window for delay calculation (seconds)
            
        Returns:
            times: Array of time points
            delays: Array of average delay values
        """
        if self.data is None:
            return [], []
        
        target_dest_mac = '0A-AA-00-00-00-02'
        
        # Group by treeId to calculate per-packet delays
        packet_delays = {}
        grouped = self.data.groupby('treeId')
        
        for tree_id, group in grouped:
            group = group.sort_values('simTime')
            
            # Check if packet was delivered
            if target_dest_mac in group['destMacAddress'].values:
                start_time = group['simTime'].iloc[0]
                end_time = group[group['destMacAddress'] == target_dest_mac]['simTime'].iloc[0]
                delay = end_time - start_time
                packet_delays[tree_id] = (end_time, delay)
        
        # Calculate average delay over time windows
        min_time = self.data['simTime'].min()
        max_time = self.data['simTime'].max()
        
        times = []
        delays = []
        
        current_time = min_time + time_window
        while current_time <= max_time:
            # Get packets delivered in current time window
            window_delays = [
                delay for tree_id, (delivery_time, delay) in packet_delays.items()
                if current_time - time_window <= delivery_time < current_time
            ]
            
            if window_delays:
                avg_delay = np.mean(window_delays)
                times.append(current_time)
                delays.append(avg_delay)
            
            current_time += time_window / 2
        
        return np.array(times), np.array(delays)
    
    def calculate_energy_efficiency_over_time(self, time_window=10.0):
        """
        Calculate energy efficiency over time
        
        Args:
            time_window: Time window for energy calculation (seconds)
            
        Returns:
            times: Array of time points
            efficiency: Array of energy efficiency values
        """
        if self.data is None:
            return [], []
        
        min_time = self.data['simTime'].min()
        max_time = self.data['simTime'].max()
        
        times = []
        efficiencies = []
        
        current_time = min_time + time_window
        while current_time <= max_time:
            # Get data in current time window
            window_data = self.data[
                (self.data['simTime'] >= current_time - time_window) &
                (self.data['simTime'] < current_time)
            ]
            
            if len(window_data) > 0:
                # Calculate average residual energy
                avg_energy = window_data['residualEnergy'].mean()
                
                # Calculate energy efficiency (higher residual energy = better efficiency)
                efficiency = avg_energy * 100  # Convert to percentage
                
                times.append(current_time)
                efficiencies.append(efficiency)
            
            current_time += time_window / 2
        
        return np.array(times), np.array(efficiencies)
    
    def calculate_reward_over_time(self, time_window=10.0):
        """
        Calculate estimated reward over time based on PDR, delay, and energy
        
        Args:
            time_window: Time window for reward calculation (seconds)
            
        Returns:
            times: Array of time points
            rewards: Array of reward values
        """
        # Get individual metrics
        pdr_times, pdrs = self.calculate_pdr_over_time(time_window)
        delay_times, delays = self.calculate_delay_over_time(time_window)
        energy_times, energies = self.calculate_energy_efficiency_over_time(time_window)
        
        # Find common time points
        all_times = set(pdr_times) & set(delay_times) & set(energy_times)
        common_times = sorted(all_times)
        
        rewards = []
        
        for time in common_times:
            # Get values at this time point
            pdr_idx = np.argmin(np.abs(pdr_times - time))
            delay_idx = np.argmin(np.abs(delay_times - time))
            energy_idx = np.argmin(np.abs(energy_times - time))
            
            pdr = pdrs[pdr_idx] / 100.0  # Convert back to ratio
            delay = delays[delay_idx] if len(delays) > delay_idx else 0
            energy_eff = energies[energy_idx] / 100.0  # Convert back to ratio
            
            # Calculate composite reward
            reward = pdr - 0.01 * delay - 0.1 * (1 - energy_eff)
            rewards.append(reward)
        
        return np.array(common_times), np.array(rewards)
    
    def smooth_curve(self, values):
        """Apply moving average smoothing to a curve"""
        if len(values) < self.window_size:
            return values
        return uniform_filter1d(values, size=min(self.window_size, len(values)))
    
    def plot_learning_curves(self, save_plots=True, output_dir='.'):
        """
        Plot comprehensive learning curves
        
        Args:
            save_plots: Whether to save plots to files
            output_dir: Directory to save plots
        """
        if self.data is None:
            print("No data loaded. Please call load_data() first.")
            return
        
        # Set style
        plt.style.use('seaborn-v0_8')
        sns.set_palette("husl")
        
        # Create subplots
        fig, axes = plt.subplots(2, 2, figsize=(15, 12))
        fig.suptitle('MLMORP Reinforcement Learning - Learning Curves', fontsize=16)
        
        # 1. Packet Delivery Ratio
        pdr_times, pdrs = self.calculate_pdr_over_time()
        if len(pdr_times) > 0:
            pdrs_smooth = self.smooth_curve(pdrs)
            axes[0, 0].plot(pdr_times, pdrs, alpha=0.3, color='blue', label='Raw')
            axes[0, 0].plot(pdr_times, pdrs_smooth, color='blue', linewidth=2, label='Smoothed')
            axes[0, 0].set_title('Packet Delivery Ratio Over Time')
            axes[0, 0].set_xlabel('Simulation Time (s)')
            axes[0, 0].set_ylabel('PDR (%)')
            axes[0, 0].grid(True, alpha=0.3)
            axes[0, 0].legend()
            axes[0, 0].set_ylim(0, 100)
        
        # 2. Average Delay
        delay_times, delays = self.calculate_delay_over_time()
        if len(delay_times) > 0:
            delays_smooth = self.smooth_curve(delays)
            axes[0, 1].plot(delay_times, delays, alpha=0.3, color='red', label='Raw')
            axes[0, 1].plot(delay_times, delays_smooth, color='red', linewidth=2, label='Smoothed')
            axes[0, 1].set_title('Average Packet Delay Over Time')
            axes[0, 1].set_xlabel('Simulation Time (s)')
            axes[0, 1].set_ylabel('Delay (s)')
            axes[0, 1].grid(True, alpha=0.3)
            axes[0, 1].legend()
        
        # 3. Energy Efficiency
        energy_times, energies = self.calculate_energy_efficiency_over_time()
        if len(energy_times) > 0:
            energies_smooth = self.smooth_curve(energies)
            axes[1, 0].plot(energy_times, energies, alpha=0.3, color='green', label='Raw')
            axes[1, 0].plot(energy_times, energies_smooth, color='green', linewidth=2, label='Smoothed')
            axes[1, 0].set_title('Energy Efficiency Over Time')
            axes[1, 0].set_xlabel('Simulation Time (s)')
            axes[1, 0].set_ylabel('Residual Energy (%)')
            axes[1, 0].grid(True, alpha=0.3)
            axes[1, 0].legend()
        
        # 4. Composite Reward
        reward_times, rewards = self.calculate_reward_over_time()
        if len(reward_times) > 0:
            rewards_smooth = self.smooth_curve(rewards)
            axes[1, 1].plot(reward_times, rewards, alpha=0.3, color='purple', label='Raw')
            axes[1, 1].plot(reward_times, rewards_smooth, color='purple', linewidth=2, label='Smoothed')
            axes[1, 1].set_title('Composite Reward Over Time')
            axes[1, 1].set_xlabel('Simulation Time (s)')
            axes[1, 1].set_ylabel('Reward')
            axes[1, 1].grid(True, alpha=0.3)
            axes[1, 1].legend()
        
        plt.tight_layout()
        
        if save_plots:
            output_path = os.path.join(output_dir, 'learning_curves.png')
            plt.savefig(output_path, dpi=300, bbox_inches='tight')
            print(f"Learning curves saved to {output_path}")
        
        plt.show()
    
    def plot_network_metrics(self, save_plots=True, output_dir='.'):
        """
        Plot additional network metrics
        
        Args:
            save_plots: Whether to save plots to files
            output_dir: Directory to save plots
        """
        if self.data is None:
            print("No data loaded. Please call load_data() first.")
            return
        
        fig, axes = plt.subplots(2, 2, figsize=(15, 12))
        fig.suptitle('MLMORP Network Metrics Over Time', fontsize=16)
        
        # 1. Node Degree Distribution
        time_windows = np.linspace(self.data['simTime'].min(), self.data['simTime'].max(), 20)
        avg_degrees = []
        
        for i in range(len(time_windows) - 1):
            window_data = self.data[
                (self.data['simTime'] >= time_windows[i]) &
                (self.data['simTime'] < time_windows[i + 1])
            ]
            if len(window_data) > 0:
                avg_degrees.append(window_data['nodeDegree'].mean())
            else:
                avg_degrees.append(0)
        
        axes[0, 0].plot(time_windows[:-1], avg_degrees, marker='o')
        axes[0, 0].set_title('Average Node Degree Over Time')
        axes[0, 0].set_xlabel('Simulation Time (s)')
        axes[0, 0].set_ylabel('Average Node Degree')
        axes[0, 0].grid(True, alpha=0.3)
        
        # 2. Buffer Utilization
        avg_buffers = []
        for i in range(len(time_windows) - 1):
            window_data = self.data[
                (self.data['simTime'] >= time_windows[i]) &
                (self.data['simTime'] < time_windows[i + 1])
            ]
            if len(window_data) > 0:
                avg_buffers.append(window_data['buffPktNo'].mean())
            else:
                avg_buffers.append(0)
        
        axes[0, 1].plot(time_windows[:-1], avg_buffers, marker='o', color='orange')
        axes[0, 1].set_title('Average Buffer Utilization Over Time')
        axes[0, 1].set_xlabel('Simulation Time (s)')
        axes[0, 1].set_ylabel('Average Buffer Packets')
        axes[0, 1].grid(True, alpha=0.3)
        
        # 3. Signal Power Distribution
        axes[1, 0].hist(self.data['signalPower'], bins=50, alpha=0.7, color='cyan')
        axes[1, 0].set_title('Signal Power Distribution')
        axes[1, 0].set_xlabel('Signal Power')
        axes[1, 0].set_ylabel('Frequency')
        axes[1, 0].grid(True, alpha=0.3)
        
        # 4. Data Rate Over Time
        avg_rates = []
        for i in range(len(time_windows) - 1):
            window_data = self.data[
                (self.data['simTime'] >= time_windows[i]) &
                (self.data['simTime'] < time_windows[i + 1])
            ]
            if len(window_data) > 0:
                avg_rates.append(window_data['dataRate'].mean())
            else:
                avg_rates.append(0)
        
        axes[1, 1].plot(time_windows[:-1], np.array(avg_rates) / 1e6, marker='o', color='red')
        axes[1, 1].set_title('Average Data Rate Over Time')
        axes[1, 1].set_xlabel('Simulation Time (s)')
        axes[1, 1].set_ylabel('Average Data Rate (Mbps)')
        axes[1, 1].grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        if save_plots:
            output_path = os.path.join(output_dir, 'network_metrics.png')
            plt.savefig(output_path, dpi=300, bbox_inches='tight')
            print(f"Network metrics saved to {output_path}")
        
        plt.show()
    
    def generate_summary_report(self):
        """Generate a summary report of the learning performance"""
        if self.data is None:
            print("No data loaded. Please call load_data() first.")
            return
        
        print("\n" + "="*60)
        print("MLMORP REINFORCEMENT LEARNING SUMMARY REPORT")
        print("="*60)
        
        # Basic statistics
        print(f"Simulation Duration: {self.data['simTime'].max() - self.data['simTime'].min():.2f} seconds")
        print(f"Total Data Points: {len(self.data)}")
        print(f"Unique Packets: {self.data['treeId'].nunique()}")
        
        # PDR statistics
        pdr_times, pdrs = self.calculate_pdr_over_time()
        if len(pdrs) > 0:
            print(f"\nPacket Delivery Ratio:")
            print(f"  Average: {np.mean(pdrs):.2f}%")
            print(f"  Final: {pdrs[-1]:.2f}%")
            print(f"  Best: {np.max(pdrs):.2f}%")
        
        # Delay statistics
        delay_times, delays = self.calculate_delay_over_time()
        if len(delays) > 0:
            print(f"\nPacket Delay:")
            print(f"  Average: {np.mean(delays):.4f}s")
            print(f"  Final: {delays[-1]:.4f}s")
            print(f"  Best: {np.min(delays):.4f}s")
        
        # Energy statistics
        energy_times, energies = self.calculate_energy_efficiency_over_time()
        if len(energies) > 0:
            print(f"\nEnergy Efficiency:")
            print(f"  Average: {np.mean(energies):.2f}%")
            print(f"  Final: {energies[-1]:.2f}%")
            print(f"  Best: {np.max(energies):.2f}%")
        
        # Network statistics
        print(f"\nNetwork Metrics:")
        print(f"  Average Node Degree: {self.data['nodeDegree'].mean():.2f}")
        print(f"  Average Buffer Utilization: {self.data['buffPktNo'].mean():.2f}")
        print(f"  Average Data Rate: {self.data['dataRate'].mean()/1e6:.2f} Mbps")
        
        print("="*60)

def main():
    parser = argparse.ArgumentParser(description='Plot Learning Curves for MLMORP RL')
    parser.add_argument('--input', '-i', default='../results/output.csv',
                       help='Input CSV file with simulation data')
    parser.add_argument('--output-dir', '-o', default='.',
                       help='Output directory for plots')
    parser.add_argument('--window-size', type=int, default=50,
                       help='Moving average window size for smoothing')
    parser.add_argument('--time-window', type=float, default=10.0,
                       help='Time window for metric calculations (seconds)')
    parser.add_argument('--no-save', action='store_true',
                       help='Do not save plots to files')
    parser.add_argument('--summary-only', action='store_true',
                       help='Only generate summary report, no plots')
    
    args = parser.parse_args()
    
    # Check if input file exists
    if not os.path.exists(args.input):
        print(f"Error: Input file {args.input} not found!")
        print("Please run the OMNeT++ simulation first to generate the data file.")
        return
    
    # Create output directory if it doesn't exist
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)
    
    # Create plotter
    plotter = LearningCurvePlotter(window_size=args.window_size)
    
    # Load data
    if not plotter.load_data(args.input):
        return
    
    # Generate summary report
    plotter.generate_summary_report()
    
    if not args.summary_only:
        # Plot learning curves
        plotter.plot_learning_curves(save_plots=not args.no_save, output_dir=args.output_dir)
        
        # Plot network metrics
        plotter.plot_network_metrics(save_plots=not args.no_save, output_dir=args.output_dir)
    
    print(f"\nAnalysis completed!")

if __name__ == "__main__":
    main()

