//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/routing/mmlrp/Mmlrp.msg.
//

#ifndef __INET_MMLRP_M_H
#define __INET_MMLRP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class MmlrpBeacon;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/contract/ipv4/Ipv4Address_m.h" // import inet.networklayer.contract.ipv4.Ipv4Address


namespace inet {

/**
 * Class generated from <tt>inet/routing/mmlrp/Mmlrp.msg:9</tt> by opp_msgtool.
 * <pre>
 * class MmlrpBeacon extends FieldsChunk
 * {
 *     Ipv4Address srcAddress;        //Node that generate the Beacon
 *     unsigned int sequencenumber;   //sequence number created by the source node(node's ID = srcIPAddress) of the beacon msg and associated with that node
 *     Ipv4Address nextAddress;       //terminal that transmits or re-transmits the packet
 *     int distanceCost;              //distance in hops/cost
 * }
 * </pre>
 */
class INET_API MmlrpBeacon : public ::inet::FieldsChunk
{
  protected:
    Ipv4Address srcAddress;
    unsigned int sequencenumber = 0;
    Ipv4Address nextAddress;
    int distanceCost = 0;

  private:
    void copy(const MmlrpBeacon& other);

  protected:
    bool operator==(const MmlrpBeacon&) = delete;

  public:
    MmlrpBeacon();
    MmlrpBeacon(const MmlrpBeacon& other);
    virtual ~MmlrpBeacon();
    MmlrpBeacon& operator=(const MmlrpBeacon& other);
    virtual MmlrpBeacon *dup() const override {return new MmlrpBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Ipv4Address& getSrcAddress() const;
    virtual Ipv4Address& getSrcAddressForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MmlrpBeacon*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const Ipv4Address& srcAddress);

    virtual unsigned int getSequencenumber() const;
    virtual void setSequencenumber(unsigned int sequencenumber);

    virtual const Ipv4Address& getNextAddress() const;
    virtual Ipv4Address& getNextAddressForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MmlrpBeacon*>(this)->getNextAddress());}
    virtual void setNextAddress(const Ipv4Address& nextAddress);

    virtual int getDistanceCost() const;
    virtual void setDistanceCost(int distanceCost);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MmlrpBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MmlrpBeacon& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::MmlrpBeacon *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::MmlrpBeacon*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MMLRP_M_H

