//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/routing/mlmorp/Mlmorp.msg.
//

#ifndef __INET_MLMORP_M_H
#define __INET_MLMORP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class MlmorpBeacon;
class MlmorpAck;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/contract/ipv4/Ipv4Address_m.h" // import inet.networklayer.contract.ipv4.Ipv4Address

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry


namespace inet {

/**
 * Class generated from <tt>inet/routing/mlmorp/Mlmorp.msg:12</tt> by opp_msgtool.
 * <pre>
 * class MlmorpBeacon extends FieldsChunk
 * {
 *     Ipv4Address srcAddress;        // Node that generate the beacon
 *     Ipv4Address nextAddress;       // Node that transmits or re-transmits the packet    
 *     unsigned int sequenceNumber;   // Sequence number created by the source node of the beacon msg
 *     float cost;                    // Cost to reach the source node
 * 
 *     Coord nextPosition;            // Position of the next node
 *     int nodeDegree;                // Number of neighbors
 *     double residualEnergy;         // The residual energy of the node
 *     double dataRate;               // The data rate of the node
 * 
 *     double signalPower;            // Signal power in dBm
 *     double buffPktNo;              // packet buffer or packet queue of the node
 * }
 * </pre>
 */
class INET_API MlmorpBeacon : public ::inet::FieldsChunk
{
  protected:
    Ipv4Address srcAddress;
    Ipv4Address nextAddress;
    unsigned int sequenceNumber = 0;
    float cost = 0;
    Coord nextPosition;
    int nodeDegree = 0;
    double residualEnergy = 0;
    double dataRate = 0;
    double signalPower = 0;
    double buffPktNo = 0;

  private:
    void copy(const MlmorpBeacon& other);

  protected:
    bool operator==(const MlmorpBeacon&) = delete;

  public:
    MlmorpBeacon();
    MlmorpBeacon(const MlmorpBeacon& other);
    virtual ~MlmorpBeacon();
    MlmorpBeacon& operator=(const MlmorpBeacon& other);
    virtual MlmorpBeacon *dup() const override {return new MlmorpBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Ipv4Address& getSrcAddress() const;
    virtual Ipv4Address& getSrcAddressForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MlmorpBeacon*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const Ipv4Address& srcAddress);

    virtual const Ipv4Address& getNextAddress() const;
    virtual Ipv4Address& getNextAddressForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MlmorpBeacon*>(this)->getNextAddress());}
    virtual void setNextAddress(const Ipv4Address& nextAddress);

    virtual unsigned int getSequenceNumber() const;
    virtual void setSequenceNumber(unsigned int sequenceNumber);

    virtual float getCost() const;
    virtual void setCost(float cost);

    virtual const Coord& getNextPosition() const;
    virtual Coord& getNextPositionForUpdate() { handleChange();return const_cast<Coord&>(const_cast<MlmorpBeacon*>(this)->getNextPosition());}
    virtual void setNextPosition(const Coord& nextPosition);

    virtual int getNodeDegree() const;
    virtual void setNodeDegree(int nodeDegree);

    virtual double getResidualEnergy() const;
    virtual void setResidualEnergy(double residualEnergy);

    virtual double getDataRate() const;
    virtual void setDataRate(double dataRate);

    virtual double getSignalPower() const;
    virtual void setSignalPower(double signalPower);

    virtual double getBuffPktNo() const;
    virtual void setBuffPktNo(double buffPktNo);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MlmorpBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MlmorpBeacon& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/routing/mlmorp/Mlmorp.msg:28</tt> by opp_msgtool.
 * <pre>
 * class MlmorpAck extends FieldsChunk
 * {
 *     int treeId;                     // Tree ID of the original packet being acknowledged
 *     Ipv4Address originalSource;    // Original source address of the packet
 *     Ipv4Address originalDestination; // Original destination address of the packet
 *     simtime_t deliveryTime;         // Time when packet was delivered at destination
 * }
 * </pre>
 */
class INET_API MlmorpAck : public ::inet::FieldsChunk
{
  protected:
    int treeId = 0;
    Ipv4Address originalSource;
    Ipv4Address originalDestination;
    ::omnetpp::simtime_t deliveryTime = SIMTIME_ZERO;

  private:
    void copy(const MlmorpAck& other);

  protected:
    bool operator==(const MlmorpAck&) = delete;

  public:
    MlmorpAck();
    MlmorpAck(const MlmorpAck& other);
    virtual ~MlmorpAck();
    MlmorpAck& operator=(const MlmorpAck& other);
    virtual MlmorpAck *dup() const override {return new MlmorpAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTreeId() const;
    virtual void setTreeId(int treeId);

    virtual const Ipv4Address& getOriginalSource() const;
    virtual Ipv4Address& getOriginalSourceForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MlmorpAck*>(this)->getOriginalSource());}
    virtual void setOriginalSource(const Ipv4Address& originalSource);

    virtual const Ipv4Address& getOriginalDestination() const;
    virtual Ipv4Address& getOriginalDestinationForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MlmorpAck*>(this)->getOriginalDestination());}
    virtual void setOriginalDestination(const Ipv4Address& originalDestination);

    virtual ::omnetpp::simtime_t getDeliveryTime() const;
    virtual void setDeliveryTime(::omnetpp::simtime_t deliveryTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MlmorpAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MlmorpAck& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::MlmorpBeacon *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::MlmorpBeacon*>(ptr.get<cObject>()); }
template<> inline inet::MlmorpAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::MlmorpAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MLMORP_M_H

