//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/routing/morp/Morp.msg.
//

#ifndef __INET_MORP_M_H
#define __INET_MORP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class MorpBeacon;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/contract/ipv4/Ipv4Address_m.h" // import inet.networklayer.contract.ipv4.Ipv4Address

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry


namespace inet {

/**
 * Class generated from <tt>inet/routing/morp/Morp.msg:12</tt> by opp_msgtool.
 * <pre>
 * class MorpBeacon extends FieldsChunk
 * {
 *     Ipv4Address srcAddress;        // Node that generate the beacon
 *     Ipv4Address nextAddress;       // Node that transmits or re-transmits the packet    
 *     unsigned int sequenceNumber;   // Sequence number created by the source node of the beacon msg
 *     float cost;                    // Cost to reach the source node
 * 
 *     Coord nextPosition;            // Position of the next node
 *     int nodeDegree;                // Number of neighbors  
 * }
 * </pre>
 */
class INET_API MorpBeacon : public ::inet::FieldsChunk
{
  protected:
    Ipv4Address srcAddress;
    Ipv4Address nextAddress;
    unsigned int sequenceNumber = 0;
    float cost = 0;
    Coord nextPosition;
    int nodeDegree = 0;

  private:
    void copy(const MorpBeacon& other);

  protected:
    bool operator==(const MorpBeacon&) = delete;

  public:
    MorpBeacon();
    MorpBeacon(const MorpBeacon& other);
    virtual ~MorpBeacon();
    MorpBeacon& operator=(const MorpBeacon& other);
    virtual MorpBeacon *dup() const override {return new MorpBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Ipv4Address& getSrcAddress() const;
    virtual Ipv4Address& getSrcAddressForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MorpBeacon*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const Ipv4Address& srcAddress);

    virtual const Ipv4Address& getNextAddress() const;
    virtual Ipv4Address& getNextAddressForUpdate() { handleChange();return const_cast<Ipv4Address&>(const_cast<MorpBeacon*>(this)->getNextAddress());}
    virtual void setNextAddress(const Ipv4Address& nextAddress);

    virtual unsigned int getSequenceNumber() const;
    virtual void setSequenceNumber(unsigned int sequenceNumber);

    virtual float getCost() const;
    virtual void setCost(float cost);

    virtual const Coord& getNextPosition() const;
    virtual Coord& getNextPositionForUpdate() { handleChange();return const_cast<Coord&>(const_cast<MorpBeacon*>(this)->getNextPosition());}
    virtual void setNextPosition(const Coord& nextPosition);

    virtual int getNodeDegree() const;
    virtual void setNodeDegree(int nodeDegree);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MorpBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MorpBeacon& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::MorpBeacon *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::MorpBeacon*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MORP_M_H

